name: CI

on: [push, pull_request ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Copy env of Validator
        run: cp env/.env.sample env/.env
      - name: Check formatting of Validator
        run: yarn run formatting:check
      - name: Compile of Validator
        run: yarn run build
      - name: Run Hardhat Tests of Validator
        env:
          REPORT_GAS: true
        run: yarn run test
